import { useEffect, useState } from "react";
import { Edit2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type Task = { id: number; taskName: string; priority?: string | null; status?: string; plannedStartDate?: string | null; plannedEndDate?: string | null };

export function TaskEditButton({ task, onComplete }: { task: Task; onComplete: () => void }) {
  const [open, setOpen] = useState(false); const [name, setName] = useState(task.taskName); const [priority, setPriority] = useState(task.priority || "medium"); const [status, setStatus] = useState(task.status || "yts"); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (open) { setName(task.taskName); setPriority(task.priority || "medium"); setStatus(task.status || "yts"); setError(""); } }, [open, task]);
  const save = async () => { if (!name.trim()) return setError("Task name is required."); setSaving(true); setError(""); try { const response = await fetch(`http://localhost:8080/api/tasks/${task.id}`, { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${localStorage.getItem("auth_token") || ""}` }, body: JSON.stringify({ taskName: name.trim(), priority, status, completionPct: status === "completed" ? 100 : status === "yts" ? 0 : undefined }) }); if (!response.ok) { const result = await response.json(); throw new Error(result.error || "Unable to update task"); } setOpen(false); onComplete(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to update task"); } finally { setSaving(false); } };
  return <><Button title="Edit Task" variant="outline" size="sm" onClick={() => setOpen(true)} className="h-8 gap-1"><Edit2 className="h-4 w-4" />Edit</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Edit Task</DialogTitle></DialogHeader><div className="space-y-3"><Input value={name} onChange={(event) => setName(event.target.value)} aria-label="Task name" /><Select value={priority} onValueChange={setPriority}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="high">High priority</SelectItem><SelectItem value="medium">Medium priority</SelectItem><SelectItem value="low">Low priority</SelectItem></SelectContent></Select><Select value={status} onValueChange={setStatus}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="yts">Not started</SelectItem><SelectItem value="wip">Work in progress</SelectItem><SelectItem value="hold">On hold</SelectItem><SelectItem value="completed">Completed</SelectItem></SelectContent></Select>{error && <p className="text-sm text-red-600">{error}</p>}</div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={save} disabled={saving}>{saving ? "Saving…" : "Save changes"}</Button></DialogFooter></DialogContent></Dialog></>;
}
